[package]
name = "ocsp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
config-file = "0.2.3"
hex = "0.4.3"
mysql = "24.0.0"
ocsp = "0.4.0"
openssl = "0.10.62"
rocket = "0.5.0"
serde = "1.0.193"
zeroize = { version = "1.7.0", features = ["std", "zeroize_derive"] }
