#Config file, all fields are compulsory
cachedays = 3
dbip = "127.0.0.1"
port = 9000
timeout = 10
dbuser = "cert"
dbpassword = "cert"
dbname = "certs"
cachefolder = "cache/"
itcert = "test_files/cert.pem"
itkey = "test_files/keyp8.pk8"
